version: '3.8'
services:
  stats-server:
    build: ./explore-with-me-statistics/statistics-service
    image: statistics-service
    container_name: statistics-service
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./explore-with-me-basic/basic-service
    image: ewm-service
    container_name: ewm-service
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SRV_HOST=stats-server
      - STATS_SRV_PORT=9090
      - EWM_DB_HOST=ewm-db
      - EWM_DB_PORT=5432
      - EWM_DB_NAME=ewm
      - EWM_POSTGRES_USER=root
      - EWM_POSTGRES_PASSWORD=root

  ewm-db:
    build: ./explore-with-me-basic/DockerPg
    image: ewm-db
    container_name: ewm-db
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  sso-service:
    build: ./explore-with-me-auth
    image: sso-service
    container_name: sso-service
    ports:
      - "9000:9000"
    depends_on:
      - ewm-db
      - ewm-service
    environment:
      - EWM_DB_HOST=ewm-db
      - EWM_DB_PORT=5432
      - EWM_DB_NAME=ewm
      - EWM_POSTGRES_USER=root
      - EWM_POSTGRES_PASSWORD=root
      - SSO_SRV_PROTO=http
      - SSO_SRV_HOST=localhost
      - SSO_SRV_PORT=9000
      - YANDEX_CLIENT_ID=your_id
      - YANDEX_CLIENT_SECRET=your_secret
      - EWM_CLIENT_REDIRECT_URI=http://127.0.0.1:9090/login/oauth2/code/ewm-client

  gateway-service:
    build: ./explore-with-me-gateway
    image: ewm-gateway-service
    container_name: ewm-gateway-service
    ports:
      - "8443:8443"
    depends_on:
      - ewm-service
      - sso-service
    environment:
      - BASIC_SRV_HOST=ewm-service
      - BASIC_SRV_PORT=8080
      - SSO_SRV_PROTO=http
      - SSO_SRV_HOST=sso-service
      - SSO_SRV_PORT=9000
      - SSO_JWKS_PATH=/oauth2/jwks
