version: '3.1'
services:
  stats-server:
    build: ./explore-with-me-statistics/statistics-service
    image: statistics-service
    container_name: statistics-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./explore-with-me-basic
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SRV_HOST=stats-server
      - STATS_SRV_PORT=9090
      - EWM_DB_HOST=ewm-db
      - EWM_DB_PORT=5432
      - EWM_DB_NAME=ewm
      - EWM_POSTGRES_USER=root
      - EWM_POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
